services:

  devcontainer:
    image: ${DEVCONTAINER_IMAGE}
    pull_policy: always
    volumes:
      - ../:/workspaces/content:cached  # always mount to same folder
      - ${PROGRESS_CFG}:/usr/dlc/progress.cfg:ro
      #- /var/run/docker.sock:/var/run/docker.sock  # only if really needed
    # ports:
    #   - ${DEBUG_PORT}:3099
    command: sleep infinity

