services:

  devcontainer:
    image: ${DEVCONTAINER_IMAGE}
    pull_policy: always
    volumes:
      - ../..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PROGRESS_CFG}:/usr/dlc/progress.cfg
    # ports:
    #   - ${DEBUG_PORT}:3099
    command: sleep infinity

